---
- include_tasks: dependencies.yml
  tags:
    - docker_dependencies

- include_tasks: apt_repo.yml
  tags:
    - docker_dependencies

- name: "Install docker package with apt"
  apt:
    state: present
    name: "{{ docker_packages }}"
  notify: restart docker
  tags:
    - docker_package

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
  tags:
    - docker_service

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: get_docker_compose.yml
  when: docker_install_compose|bool
  tags:
    - docker-compose
