---
- name: "Remove old versions of docker with apt"
  apt:
    name: "{{ old_docker_packages }}"
    state: absent
  become: true
  tags:
    - docker_dependencies

- name: "Install docker dependencies with apt"
  apt:
    name: "{{ docker_dependencies }}"
    update_cache: true
    cache_valid_time: 3600
    state: present
  tags:
    - docker_dependencies

- name: "Add docker gpg key with apt_key"
  apt_key:
    state: present
    url: "{{ docker_gpg_key }}"
  tags:
    - docker_package

- name: "Add docker apt repository with apt_repository"
  apt_repository:
    state: present
    repo: "{{ docker_repo }}"
  tags:
    - docker_package

- name: "Install docker package with apt"
  apt:
    state: present
    name: "{{ docker_packages }}"
  notify: restart docker
  tags:
    - docker_package

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
  tags:
    - docker_service

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: get_docker_compose.yml
  when: docker_install_compose|bool
  tags:
    - docker-compose
