# Handler file for gucharbon.setup_docker role.
---
- name: restart docker
  service:
    name: docker
    state: "{{ docker_restart_handler_state }}"

- name: update apt cache
  apt:
    update_cache: yes
